public with sharing class WarnForNoSubmissionActivator {
    public WarnForNoSubmissionActivator() {
        // ABHI this class is going to run every 15th of the month and the 25th of the month. This class will check if the user has submitted the feedback form for the month. If not, it will send an email to the user and their manager as well, given a form exists for the department and month. We will schedule this.

        

    }
}